### ISSUE TITLE
project instead of description

### ISSUE THREAD

**Issue by bepolymathe** [monban/intheam-webextension#12]
Hello,

I'm trying the extension. The connection with inthe. am works but there is an error on the field. The "Project" field takes the place of the "description". 
Do you have the same problem?

**Comment by monban** [comment]
Confirmed. When submitting a task with no project, everything works as planned. When submitting with a project, the submitted project name is placed into the description field and the project is left blank.

**Comment by monban** [comment]
New version published to web stores, should be available for update tomorrow sometime.

**Comment by bepolymathe** [comment]
Thanks !
