### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by bepolymathe** [monban/intheam-webextension#13]
Hi,
I noticed that if I put quotation marks in the description text... I have a problem with `&dquot;` type encoding once I synchronized with my local Taskwarrior instance. Same problem with Taskwarrior2 on Android...
Wouldn't that be due to the absence of UTF8?
Regards

**Comment by monban** [comment]
Confirmed. I am pretty sure this is happening when the strings get bundled to be sent to the server. Specifically `JSON.stringify` is called to turn the object into JSON before sending to the server. This happens [on line 20 in task.js](https://github.com/monban/intheam-webextension/blob/a6ecce673d7945a7aaa294c0a8d87406891dc459/popup/task.js#L20). I'm not sure if we can even resolve this on our end, it might need to be resolved on the inthe.am side. I'll have a look at it this weekend.

**Comment by monban** [comment]
After doing some research, I can confirm that this is a bug with inthe.am itself. I cannot fix it on this side. I will close this bug and open one on inthe.am. I might have some time to try fixing it upstream tomorrow.
